### ISSUE TITLE
Data triplication

### ISSUE THREAD

**Issue by t0mer** [mad-ady/tl-sg-prometheus-exporter#9]
HI,
Just wanted to say thank you for this project.
I have been able to change the display and remove the data triplication, will upload the fix in few days.

![image](https://github.com/mad-ady/tl-sg-prometheus-exporter/assets/4478920/b7f3a663-9c6d-4c55-934d-03e57af9e393)

**Comment by mad-ady** [comment]
Thanks for taking the time to figure it out! Please send a pull request or instructions how to fix it.
